/* Plugin Template generated by Pawn Studio */
#include <sourcemod>

new IMPULS_FLASHLIGHT = 100;
new Float:PressTime[MAXPLAYERS + 1];

new AllowedTeam;
new bool:EnableSurvivor;
new bool:EnableInfected;
new bool:EnableFlashlightToggle;
new Handle:l4d_nt_team;
new Handle:l4d_nt_flashlight_toggle;

public Plugin:myinfo = {
    name        = "Night Vision",
    author      = "Pan Xiaohai & Mr. Zero",
    description = "<- Description ->",
    version     = "1.0",
    url         = "<- URL ->"
}

public OnPluginStart()
{
    RegConsoleCmd("sm_nightvision", sm_nightvision, "Switch night vision on/off");
    l4d_nt_team = CreateConVar("l4d_nt_team", "1", "设置为哪些阵营启用夜视仪\n0:禁用，1:为幸存者和感染者启用，2:为幸存者启用，3:为感染者启用");
    l4d_nt_flashlight_toggle = CreateConVar("l4d_nt_flashlight_toggle", "0", "设置是否允许通过双击手电筒开关启用夜视仪")
	AutoExecConfig(true, "l4d_nightvision"); 
    HookConVarChange(l4d_nt_team, ConVarChange);
    HookConVarChange(l4d_nt_flashlight_toggle, ConVarChange);
    GetConVar();
}

public ConVarChange(Handle:convar, const String:oldValue[], const String:newValue[])
{
    GetConVar();
}

GetConVar()
{
    AllowedTeam = GetConVarInt(l4d_nt_team);
    EnableSurvivor = (AllowedTeam == 1 || AllowedTeam == 2);
    EnableInfected = (AllowedTeam == 1 || AllowedTeam == 3);

    new flashlightToggle = GetConVarInt(l4d_nt_flashlight_toggle);
    if (flashlightToggle == 0 || flashlightToggle == 1)
    {
        EnableFlashlightToggle = (flashlightToggle == 1);
    }
}

public Action:sm_nightvision(client, args)
{
    if (IsClientInGame(client))
    {
        SwitchNightVision(client);
    }
    return Plugin_Handled;
}

// code from "Block Flashlight",
public Action:OnPlayerRunCmd(client, &buttons, &impuls, Float:vel[3], Float:angles[3], &weapon)
{
    if (AllowedTeam == 0 || !EnableFlashlightToggle)
    {
        return;
    }

    if (impuls == IMPULS_FLASHLIGHT)
    {
        new team = GetClientTeam(client);
        if (team == 2 && EnableSurvivor)
        {
            new Float:time = GetEngineTime();
            if (time - PressTime[client] < 0.3)
            {
                SwitchNightVision(client);
            }
            PressTime[client] = time;
        }
        if (team == 3 && EnableInfected)
        {
            new Float:time = GetEngineTime();
            if (time - PressTime[client] > 0.1)
            {
                SwitchNightVision(client);
            }
            PressTime[client] = time;
        }
    }
}

SwitchNightVision(client)
{
    new d = GetEntProp(client, Prop_Send, "m_bNightVisionOn");
    if (d == 0)
    {
        SetEntProp(client, Prop_Send, "m_bNightVisionOn", 1);
		// PrintHintText(client, "夜视仪开启");
    }
    else
    {
        SetEntProp(client, Prop_Send, "m_bNightVisionOn", 0);
		// PrintHintText(client, "夜视仪关闭");
    }
}